name: preflight

on:
  workflow_call:
    inputs:
      image_tar_name:
        required: true
        type: string

env:
  PREFLIGHT_VERSION: "1.2.1"

jobs:
  preflight:
    name: Run preflight on image
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.image_tar_name }}
        path: /tmp
    - name: Run preflight on image
      run: |
        hack/build/ci/preflight.sh "${{ env.PREFLIGHT_VERSION }}" "/tmp/${{ inputs.image_tar_name }}"
