name: Publish images

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  prepare:
    name: Prepare properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare build parameters
        id: prep
        run: |
          hack/build/ci/prepare-build-variables.sh
    outputs:
      labels: ${{ steps.prep.outputs.docker_image_labels }}
      version: ${{ steps.prep.outputs.docker_image_tag }}
      goargs: ${{ steps.prep.outputs.go_build_args }}
      goversion: ${{ steps.prepenv.outputs.goversion }}

#  # Workflow needs to build docker images again as separate workflows don't have access to others artifacts
#  # https://github.com/actions/download-artifact/issues/3
#  build-amd64:
#    name: Build image amd64
#    needs: [prepare]
#    with:
#      platform: amd64
#      goversion: ${{ needs.prepare.outputs.goversion }}
#      goargs: ${{ needs.prepare.outputs.goargs }}
#      labels: ${{ needs.prepare.outputs.labels }}
#      image-tag: ${{ needs.prepare.outputs.version }}
#    uses: ./.github/workflows/build-dockerimage.yaml
#
#  push:
#    name: Push to quay
#    needs: [prepare, build-amd64]
#    uses: ./.github/workflows/upload-dockerimage.yaml
#    with:
#      platform: amd64
#      labels: ${{ needs.prepare.outputs.labels }}
#      version: ${{ needs.prepare.outputs.version }}
#      registry: quay.io
#      repository: dynatrace/dynatrace-operator
#    secrets:
#      docker_repo_username: ${{ secrets.QUAY_USERNAME }}
#      docker_repo_password: ${{ secrets.QUAY_PASSWORD }}

  preflight:
    name: Validate image with RedHat's preflight tool
#    needs: [prepare, push]
    uses: ./.github/workflows/preflight.yaml
    with:
      platform: amd64
      version: ${{ needs.prepare.outputs.version }}
